### ISSUE TITLE
WP-CLI integration doesn't work for me

### ISSUE THREAD

**Issue by danielbachhuber** [dsawardekar/wordpress.vim#10]
Hi, first time Vim plugin user here. I followed the installation instructions in the README. When I use `Wplugin`, I get this error:

![image](https://cloud.githubusercontent.com/assets/36432/2796922/aae6d3a4-cc1c-11e3-997d-9ffa2cec6966.png)

The help docs appear fine. What am I doing wrong, or what further debugging should I do?

**Comment by dsawardekar** [comment]
That looks like a bug. The plugin calls `wp cli cmd-dump` to get a list of wp cli commands and builds the corresponding `W{command}` ex command. But if wp-cli is not detected the ex commands are not created. Hence the `not an editor command` message.

Can you post the output of directly running `wp cli info` and `wp cli cmd-dump` in the same directory.

**Comment by dsawardekar** [comment]
@danielbachhuber Did you figure this out?

I'd love to get this working if it's still broken for you, but I need more information to go on!

**Comment by danielbachhuber** [comment]
Haven't had a chance to come back to it yet

**Comment by tnorthcutt** [comment]
@danielbachhuber any chance this was happening because you were running in a Vagrant setup? I'm guessing that `Wplugin` only works if WP-CLI is availably locally, not in the guest box.

Apologies if I'm off base.

**Comment by dsawardekar** [comment]
@tnorthcutt Yes possibly. It's equivalent to just calling `$ wp foo` in the command line. If that's setup to work on the Vagrant box, it should work too. The plugin basically `cd`s into the specific project directory and executes these wp-cli commands and captures their output.

**Comment by danielbachhuber** [comment]
Sorry, user error :) I ran it in home instead of a working WordPress directory.

So, it would probably be better to say "this is not a working WordPress directory" instead of "not an editor command"

**Comment by dsawardekar** [comment]
@danielbachhuber Yeah, the error message could be better.

What I've tried to do is make the list of commands dynamic. It calls `wp cli cmd-dump` to build a list of commands and only then creates Vim's ex commands. Hence the `not an editor message`, if wp-cli was not found.

I'll mark this as an enhancement.

**Comment by dsawardekar** [comment]
This is fixed in `0.1.15`. WordPress.vim now shows an error message if WP-CLI is not detected.
