### ISSUE TITLE
Would you be interested in hosting the syntax checker for wordpress filetype?

### ISSUE THREAD

**Issue by sudar** [dsawardekar/wordpress.vim#20]
Context https://github.com/scrooloose/syntastic/issues/1180

I have created a syntax checker for wordpress filetypes for the [Syntastic](https://github.com/scrooloose/syntastic) plugin, but since it is a very niche filetype they are not interested in hosting it up.

Would you be interested in hosting it? If yes, then I can send a pull request.

**Comment by dsawardekar** [comment]
@sudar Absolutely!, I would love to have this. This is something that was also on my radar. 

When I looked at phpcs previously it was a case of calling it with `--standard=WordPress`. I'm a little busy for the next few days but I'll take a look at the details shortly.

**Comment by sudar** [comment]
No problem and thanks for your interest.

I will send a pull request with instructions over the weekend.

**Comment by dsawardekar** [comment]
Thanks again for this, it's an awesome addition to WordPress.vim! 

And sorry about the delay in getting this merged.

**Comment by sudar** [comment]
No problem at all for the delay and thanks for merging the changes :)
