### ISSUE TITLE
Allow adding custom exclude dirs for tags.

### ISSUE THREAD

**Issue by LeighBicknell** [dsawardekar/wordpress.vim#29]
Maybe something like 
g:wordpress_tags_exclude_dirs = ['_archive', '_archived']

Great plugin btw.

**Comment by sudar** [comment]
@FlickerBean 

FYI, you can also exclude directories by specifying them in `~/.ctags` file.

For example following is the contents of my `~/.ctags` file

```
--exclude=.git
--exclude=.svn
--exclude=dist
--exclude=node_modules
--exclude=vendor
--exclude=*.min.js
```

**Comment by LeighBicknell** [comment]
Actually, no I didn't know this, I've always added these into my vimrc mapping to generate tags. Thanks!
