### ISSUE TITLE
README uses outdated syntastic standard assignment syntax

### ISSUE THREAD

**Issue by salcode** [dsawardekar/wordpress.vim#32]
The documentation in [syntax_checkers/README.md](https://github.com/dsawardekar/wordpress.vim/blob/develop/syntax_checkers/README.md) is using an outdated (and no longer supported) style Syntastic standard assignment

```
let g:syntastic_wordpress_phpcs_standard = "WordPress-Core"
```

The new version is

```
let g:syntastic_php_phpcs_args = '--standard=WordPress-Core'
```

I'm not sure when this changed.

Thanks for all the great work :+1:

**Comment by sudar** [comment]
@salcode 

By new version do you mean that syntastic has changed the syntax?

We are using a custom syntax checker for WordPress and I am not sure what you mean by new syntax.

**Comment by salcode** [comment]
My apologies.  I need to remember not to open an issue after a late night of coding and wait until I have a chance to look at the problem with fresh eyes. :smile: 

The problem was completely on my end.  I thought syntastic had changed the syntax but I was **wrong**.

Sorry for the false issue.

**Comment by sudar** [comment]
Not a problem at all and glad to know that you figured it out :)

Late night coding sessions, FTW ;)
