### ISSUE TITLE
Extending WordPress snippets

### ISSUE THREAD

**Issue by sudar** [dsawardekar/wordpress.vim#4]
Good to know that there is someone else who likes both WordPress and vim :)

I maintain a [vim WordPress snippets](https://github.com/sudar/vim-wordpress-snippets) repo which contains some of my most used snippets for WordPress.

I was planning to add more snippets and also convert them to UltiSnips format from vim-snipmate format. And before I could do that I found your repo. I think that it would make more sense for your repo to have the snippets.

Would you be interested in merging the snippets that I have into your repo? If yes, then I can clean up my snippets, convert them into UltiSnips format and can send a pull request.

**Comment by dsawardekar** [comment]
PRs are welcome. :)

Snippets were on my todo list, here's some of my notes.

The main issue with my existing snippets is that they require too many placeholders. I think snippets are like Web Forms. Just as a form with too many input fields is unlikely to be filled, a snippet with too many placeholders is not going to get used.

I think 2-3 placeholders is ideal. And anything over 4 is too many.

A related issue is with size of the snippets. For instance the current `custom_post_type` snippet is big enough to require pagination. My thinking is that such snippets should be split into smaller ones, like `cpt_labels` and `cpt_args`.

I'm not very familiar with `snipmate` but UltiSnips has really good support for interpolation. That's one way to cut down on the number of placeholders. 

See the [contributing.md](https://github.com/dsawardekar/wordpress.vim/blob/develop/CONTRIBUTING.md) for details on setting up a dev environment.
