### ISSUE TITLE
Error running :helptags

### ISSUE THREAD

**Issue by tnorthcutt** [dsawardekar/wordpress.vim#7]
Caveat: I don't know much (anything, really) about how helptags generation works, but when I install wordpress.vim with Vundle, any time I run `:BundleInstall` or (after initial installation) `:BundleInstall!`, Vundle throws an error:

```
Error running :helptags /Users/travis/dotfiles/vim/bundle/wordpress.vim/doc
```

**Comment by dsawardekar** [comment]
Good catch! There were some duplicate tags in the Vim docs. I've removed them in 0.1.9. This should resolve the issue with Vundle as well.

**Comment by tnorthcutt** [comment]
Awesome, thanks! I noticed the duplicate tags previously (errors on starting Vim), but couldn't figure out where they were, so I thought maybe it was a local configuration issue for me. Glad this bug report was helpful! Thanks for a super fast resolution.
