### ISSUE TITLE
Problem with phpDoc

### ISSUE THREAD

**Issue by sudar** [dsawardekar/wordpress.vim#8]
I use [Doxygen Toolkit](https://github.com/vim-scripts/DoxygenToolkit.vim) to syntax highlight and generate/format the phpDoc comments in front of classes and functions.

When the `php.wordpress` filetype is enabled this (phpDoc formatting) is broken. If I set the filetype to `php`, the it works fine.

I also found this issue if I disable wordpress.vim, but enable only StanAngeloff/php.vim. But I was able to fix it by adding the following lines in my ~/.vimrc

```
let php_ignore_phpdoc=1
```

But once wordpress.vim is enabled, irrespective of the above line, phpDoc formatting is still broken. I guess there is some issue in how wordpress.vim calls php.vim, but I am not able to identify it in the code.

Is wordpress.vim doing any special processing on phpdoc comments?

**Comment by dsawardekar** [comment]
> Is wordpress.vim doing any special processing on phpdoc comments?

None that I can see in the [syntax file](https://github.com/dsawardekar/wordpress.vim/blob/develop/syntax/wordpress.vim). It's just keywords that are linked to and added to the cluster from php.vim.

Can you verify if it's a `wordpress.vim` issue by setting `g:wordpress_vim_php_syntax_highlight=0` in your vimrc. That will disable WordPress.vim's custom syntax highlighting entirely.

**Comment by sudar** [comment]
> Can you verify if it's a wordpress.vim issue by setting g:wordpress_vim_php_syntax_highlight=0 in your vimrc. That will disable WordPress.vim's custom syntax highlighting entirely.

I added `let g:wordpress_vim_php_syntax_highlight=0` to my vimrc file.

Even after that as long as the file type is `php.wordpress` phpdoc is not working properly. The moment I manually change the file to `php` using the command `set ft=php` it works properly.

**Comment by dsawardekar** [comment]
Interesting. I'm using `set filetype=php.wordpress`. This is standard Viml to combine syntax highlighting between different file types. It makes Vim load php syntax first(ie:- php.vim), followed by wordpress(ie:- wordpress.vim).

I'm not using the Doxygen plugin but I'll take a look. Can you be specific with the steps to reproduce the error you are having?

**Comment by sudar** [comment]
Thanks for taking time to look into the issue.

Following are the steps to reproduce it.

Let's say I have a simple php code like below

``` php
class test {
    function test() {

    }
}
```

Now when I set `ft=php` and type `/**` and then press enter, `*` automatically appears in the second line, so it becomes like this.

``` php
/**
 *
class test {
    function test() {

    }
}
```

But if the filetype is `php.wordpress` and type `/**` and then press enter, `*` doesn't automatically appears in the second line, so it becomes like this.

``` php
/**

class test {
    function test() {

    }
}
```

Let me know if it clear or if you have any questions.

**Comment by dsawardekar** [comment]
Ok I was able to reproduce the bug. Works with ft=php, does not work with ft=php.wordpress

However I don't think this feature is provided by DoxygenToolkit. I see the same functionality on stock Vim without the plugin. I checked to see if the plugin was bundled, but couldn't find it in the stock Vim `/usr/share`.

Perhaps bundled `php.vim` adds this in some way. I'm unfamiliar with how this works though. 

What part of Vim or plugin determines that a `*` is a comment and hitting enter should continue the comment on the next line?

**Comment by dsawardekar** [comment]
Ok figured it out. This is done in indent files. The PHP indent file is provided by the [PHP Indenting for Vim](https://github.com/2072/PHP-Indenting-for-VIm) plugin. I'm made a PR against it that should fix the problem.

**Comment by sudar** [comment]
Thanks for figuring it out and sending the pull request.

I would have never figured out that it was the problem with PHP Indent plugin and not yours.

Also as you said, DoxygenToolkit has nothing to do with this bug.

**Comment by dsawardekar** [comment]
Closing this as the PR has been merged upstream.

**Comment by sudar** [comment]
I can also confirm that it works now.
