### ISSUE TITLE
Duplicate helptags on install with NeoBundle

### ISSUE THREAD

**Issue by davidosomething** [dsawardekar/wordpress.vim#9]
```
Vim(helptags):E154: Duplicate tag "CtrlP" in file /Users/dotrakoun/.vim/bundle/.neobundle/doc/wordpress.txt
```

Getting this error generating helptags, not sure if it's a NeoBundle issue, a CtrlP issue, or  a Wordpress.vim issue -- but not happening with any other other plugins.

**Comment by dsawardekar** [comment]
It's a WordPress.vim issue. There was a duplicate `CtrlP` help tag in the docs that I've removed in `0.1.11`. Updating should fix the bug.

**Comment by davidosomething** [comment]
confirmed fixed! :+1:
